version: '2'
services:
    weibackstage-app:
        image: weibackstage
        external_links:
            - weibackstage-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/weibackstage?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    weibackstage-mysql:
        extends:
            file: mysql.yml
            service: weibackstage-mysql
